title: "PCT Tracker"
description: "Following a Pacific Crest Trail thru-hike, from Mexico to Canada."
url: ""  # GitHub Pages sets this
baseurl: "/pct-tracker"  # set to "/REPO_NAME" if needed
markdown: kramdown
theme: null
permalink: pretty

collections:
  updates:
    output: false
